/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rtdb_CONSTANTS_H
#define rtdb_CONSTANTS_H

#include "rtdb_types.h"

namespace rtdb {

class rtdbConstants {
 public:
  rtdbConstants();

};

extern const rtdbConstants g_rtdb_constants;

} // namespace

#endif
