/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "rtdb_constants.h"

namespace rtdb {

const rtdbConstants g_rtdb_constants;

rtdbConstants::rtdbConstants() {
}

} // namespace

